# Generated by Django 4.1 on 2022-08-30 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_alter_flashcard_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.categories'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.CharField(max_length=512),
        ),
    ]
